### ISSUE TITLE
Streamlit runtime errors

### ISSUE THREAD

**Issue by spinferno** [osi1880vr/deforum-sd-ui#22]
Hey thanks for sharing your fresh new web ui!!
Unfortunately, there is this runtime errror:
`ModuleNotFoundError: No module named 'streamlit.runtime.in_memory_file_manager'`
Do I need a custom requirements.txt to ensure that streamlit has the necessary dependencies?
Note: a fresh install does not resolve this issue.
Thanks heaps for your time!!

**Comment by osi1880vr** [comment]
Hello, 

 

for now just uncomment the line and any reference and then youre fine, or try a frsh pull maybe we fixed it already…

 

hope it will make you plenty fun =)

 

Von: BIll La ***@***.***> 
Gesendet: Freitag, 23. September 2022 14:48
An: osi1880vr/deforum-sd-ui ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [osi1880vr/deforum-sd-ui] Streamlit runtime errors (Issue #22)

 

Hey thanks for sharing your fresh new web ui!!
Unfortunately, there is this runtime errror:
ModuleNotFoundError: No module named 'streamlit.runtime.in_memory_file_manager'
Do I need a custom requirements.txt to ensure that streamlit has the necessary dependencies?
Note: a fresh install does not resolve this issue.
Thanks heaps for your time!!

**Comment by hdslave** [comment]
Spinferno was posting on my behalf. I think ive solved this issue. In the environmental.yaml file in the pip list it states "streamlit>=1.12.2" when i switched my pip to just streamlit 1.12.2 it worked. it seems something goes wrong when using the new streamlit 1.13 build

**Comment by osi1880vr** [comment]
Maybe things are moving so fast it is very hard to keep track :)

 

Von: hdslave ***@***.***> 
Gesendet: Freitag, 23. September 2022 16:13
An: osi1880vr/deforum-sd-ui ***@***.***>
Cc: osi1880vr ***@***.***>; Comment ***@***.***>
Betreff: Re: [osi1880vr/deforum-sd-ui] Streamlit runtime errors (Issue #22)

 

Bill was posting on my behalf. I think ive solved this issue. In the environmental.yaml file in the pip list it states "streamlit>1.12.2" when i switched my pip to just streamlit 1.12.2 it worked. it seems something goes wrong when using the new streamlit 1.13 build

**Comment by saruzaru** [comment]
thanks for the fix!
i'm now stuck getting this error:
```
"File "E:\ML\Deforum-SD\scripts\webui_streamlit.py", line 126, in <module>
    layout()
File "E:\ML\Deforum-SD\scripts\webui_streamlit.py", line 117, in layout
    plugins[k][0].layoutFunc()
File "E:\ML\Deforum-SD\scripts\ui\txt2vid.py", line 301, in layoutFunc
    def_runner.run_batch()
File "E:\ML\Deforum-SD\scripts\tools\deforum_runner.py", line 208, in run_batch
    generator.render_animation(args, anim_args, animation_prompts, models_path)
File "scripts\tools\deforum\generator.py", line 553, in render_animation
    sample, image = generate(args, return_latent=False, return_sample=True)
File "scripts\tools\deforum\generator.py", line 934, in generate
    if st.session_state[st.session_state["generation_mode"]]["use_GFPGAN"] == True:"
```

**Comment by osi1880vr** [comment]
Did you try the latest pull ?

 

We did see the error too but ist gone here now, but that does not mean it is fixed for you 😉

Its running on my box is just a lame excuse from the devs 😊

 

 

 

Von: Damian Zaru ***@***.***> 
Gesendet: Samstag, 24. September 2022 00:46
An: osi1880vr/deforum-sd-ui ***@***.***>
Cc: osi1880vr ***@***.***>; Comment ***@***.***>
Betreff: Re: [osi1880vr/deforum-sd-ui] Streamlit runtime errors (Issue #22)

 

thanks for the fix!
i'm now stuck getting this error:

"File "E:\ML\Deforum-SD\scripts\webui_streamlit.py", line 126, in <module>
    layout()
File "E:\ML\Deforum-SD\scripts\webui_streamlit.py", line 117, in layout
    plugins[k][0].layoutFunc()
File "E:\ML\Deforum-SD\scripts\ui\txt2vid.py", line 301, in layoutFunc
    def_runner.run_batch()
File "E:\ML\Deforum-SD\scripts\tools\deforum_runner.py", line 208, in run_batch
    generator.render_animation(args, anim_args, animation_prompts, models_path)
File "scripts\tools\deforum\generator.py", line 553, in render_animation
    sample, image = generate(args, return_latent=False, return_sample=True)
File "scripts\tools\deforum\generator.py", line 934, in generate
    if st.session_state[st.session_state["generation_mode"]]["use_GFPGAN"] == True:"

**Comment by saruzaru** [comment]
God damn, you guys move fast!

The generation all works now but I get a bug when it's trying to make a video:
```
File "E:\ml\deforum-sd\scripts\tools\deforum_runner.py", line 222, in run_batch
    video.produce_video(args, image_path, mp4_path, max_frames)
  File "scripts\tools\deforum\video.py", line 41, in produce_video
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Damian\miniconda3\envs\ldm-local\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Damian\miniconda3\envs\ldm-local\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by spinferno** [comment]
> God damn, you guys move fast!
> 
> The generation all works now but I get a bug when it's trying to make a video:
> 
> ```
> File "E:\ml\deforum-sd\scripts\tools\deforum_runner.py", line 222, in run_batch
>     video.produce_video(args, image_path, mp4_path, max_frames)
>   File "scripts\tools\deforum\video.py", line 41, in produce_video
>     process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "C:\Users\Damian\miniconda3\envs\ldm-local\lib\subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Damian\miniconda3\envs\ldm-local\lib\subprocess.py", line 1307, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> ```

Dude, thanks for reporting this, please open a new issue so that we can close of this streamlit versioning error.

**Comment by osi1880vr** [comment]
the original issue has ben solved so closed here
